export const GET_CATEGORIAS = 'get_categorias'
export const GET_PRODUCTOS_DESTACADOS = 'get_productos_destacados'
export const GET_PRODUCTOS_POR_CATEGORIA = 'get_productos_por_categoria'
export const GET_PRODUCTO = 'get_producto'
export const IS_LOADING = 'is_loading'
